#!/usr/bin/env python3
"""Build F5-TTS full-interview inputs from existing ALIUS Q/A spoken text."""

from __future__ import annotations

import json
from pathlib import Path
import re


REPO = Path(__file__).resolve().parents[1]
INTERVIEW_ID = "Issue07/Froese_Koroma"
SOURCE_DIR = REPO / "output" / "audio_interviews" / "Issue07" / "Froese_Koroma"
OUT_DIR = REPO / "output" / "voice_cloned_interviews" / "Issue07" / "Froese_Koroma"
REF_DIR = REPO / "output" / "voice_clone_sources" / "speaker_refs" / "Issue07_Froese_Koroma_enhanced"

TOM_REF_TEXT = (
    "So, you know, if you find a big surprise or prediction error on your signal, "
    "then that could be a signature of something else making difference, which is "
    "not captured in terms of the variable."
)

MATTHIEU_REF_TEXT = (
    "I don't know if you're familiar with the work of John Pence. "
    "He's a research on free will in insects and flies."
)


def extract_section(text: str, heading: str, next_heading: str | None = None) -> str:
    start = text.index(heading) + len(heading)
    end = text.index(next_heading, start) if next_heading else len(text)
    value = text[start:end].strip()
    value = re.sub(r"\s+", " ", value)
    return value


def tts_normalize(text: str) -> str:
    replacements = {
        "’": "'",
        "‘": "'",
        "“": '"',
        "”": '"',
        "–": "-",
        "—": "-",
        "…": "...",
        "ä": "a",
        "ö": "o",
        "ü": "u",
        "Ä": "A",
        "Ö": "O",
        "Ü": "U",
        "ß": "ss",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    units = []
    pieces = []
    for path in sorted(SOURCE_DIR.glob("qa_*.txt")):
        raw = path.read_text(encoding="utf-8")
        question = tts_normalize(extract_section(raw, "QUESTION SPOKEN TEXT:", "ANSWER SPOKEN TEXT:"))
        answer = tts_normalize(extract_section(raw, "ANSWER SPOKEN TEXT:"))
        index = int(path.stem.split("_")[1])
        units.append(
            {
                "index": index,
                "source": str(path),
                "question_speaker": "matthieu",
                "answer_speaker": "tom",
                "question_chars": len(question),
                "answer_chars": len(answer),
            }
        )
        pieces.append(f"[matthieu] {question}")
        pieces.append(f"[tom] {answer}")

    gen_text_path = OUT_DIR / "froese_f5_full_interview.txt"
    gen_text_path.write_text("\n\n".join(pieces) + "\n", encoding="utf-8")

    tom_ref = (REF_DIR / "tom_froese_ref_enhanced.wav").as_posix()
    matthieu_ref = (REF_DIR / "matthieu_koroma_ref_enhanced.wav").as_posix()
    output_dir = OUT_DIR.as_posix()
    gen_file = gen_text_path.as_posix()
    config = f'''model = "F5TTS_v1_Base"
ref_audio = "{tom_ref}"
ref_text = "{TOM_REF_TEXT}"
gen_text = ""
gen_file = "{gen_file}"
remove_silence = false
output_dir = "{output_dir}"
output_file = "froese_clone_full_interview.wav"
nfe_step = 16
speed = 1.0

[voices.tom]
ref_audio = "{tom_ref}"
ref_text = "{TOM_REF_TEXT}"
speed = 1.0

[voices.matthieu]
ref_audio = "{matthieu_ref}"
ref_text = "{MATTHIEU_REF_TEXT}"
speed = 1.0
'''
    config_path = OUT_DIR / "froese_f5_config.toml"
    config_path.write_text(config, encoding="utf-8")

    manifest = {
        "interview_id": INTERVIEW_ID,
        "source_dir": str(SOURCE_DIR),
        "output_dir": str(OUT_DIR),
        "config": str(config_path),
        "gen_file": str(gen_text_path),
        "units": units,
        "protocol": "Uses existing qa_*.txt QUESTION/ANSWER SPOKEN TEXT generated by the ALIUS Bulletin audio pipeline, which removes citations, brackets, URLs, and layout scaffolding.",
        "voices": {
            "tom": {
                "speaker": "Tom Froese",
                "reference_audio": tom_ref,
                "reference_text": TOM_REF_TEXT,
            },
            "matthieu": {
                "speaker": "Matthieu Koroma",
                "reference_audio": matthieu_ref,
                "reference_text": MATTHIEU_REF_TEXT,
            },
        },
    }
    (OUT_DIR / "froese_f5_input_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"wrote {config_path}")
    print(f"wrote {gen_text_path}")
    print(f"units {len(units)}")


if __name__ == "__main__":
    main()
